In [1]:
import pandas as pd
import numpy as np

# 1. Load GDP Data into a new Data Frame

In [2]:
df_gdp = pd.read_csv("../data/GDP Data.csv")
df_gdp.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.390503e+09,2.549721e+09,2.534637e+09,2.701676e+09,2.765363e+09,2.919553e+09,2.965922e+09,3.056425e+09,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,537777811.1,548888895.6,546666677.8,751111191.1,800000044.4,1.006667e+09,...,1.585657e+10,1.780429e+10,2.000160e+10,2.056107e+10,2.048489e+10,1.990711e+10,1.936264e+10,2.019176e+10,1.948438e+10,1.910135e+10
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11,1.013530e+11,9.463542e+10
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.192693e+10,1.289077e+10,1.231983e+10,1.277622e+10,1.322814e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.514702e+10,1.527808e+10
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.449967e+09,3.629204e+09,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.154058e+09

In [3]:
df_gdp.dtypes

Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1960              float64
                   ...
2015              float64
2016              float64
2017              float64
2018              float64
2019              float64
Length: 64, dtype: object

# 2. Rename columns names

In [4]:
df_gdp= df_gdp.rename({'Country Name' : 'Country',
               '2017' : 'gdp_2017'},axis=1)

In [5]:
df_gdp.head()

,Country,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2010,2011,2012,2013,2014,2015,2016,gdp_2017,2018,2019
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.390503e+09,2.549721e+09,2.534637e+09,2.701676e+09,2.765363e+09,2.919553e+09,2.965922e+09,3.056425e+09,NaN,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,537777811.1,548888895.6,546666677.8,751111191.1,800000044.4,1.006667e+09,...,1.585657e+10,1.780429e+10,2.000160e+10,2.056107e+10,2.048489e+10,1.990711e+10,1.936264e+10,2.019176e+10,1.948438e+10,1.910135e+10
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11,1.013530e+11,9.463542e+10
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.192693e+10,1.289077e+10,1.231983e+10,1.277622e+10,1.322814e+10,1.138685e+10,1.186120e+10,1.301969e+10,1.514702e+10,1.527808e+10
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.449967e+09,3.629204e+09,3.188809e+09,3.193704e+09,3.271808e+09,2.789870e+09,2.896679e+09,3.000181e+09,3.218316e+09,3.154058e+09

# 3. Drop the NaN values

In [6]:
df_gdp_new = df_gdp[['Country', 'gdp_2017']].copy()
df_gdp_new.dropna(inplace=True)
df_gdp_new.head()

       Country      gdp_2017
0        Aruba  3.056425e+09
1  Afghanistan  2.019176e+10
2       Angola  1.221240e+11
3      Albania  1.301969e+10
4      Andorra  3.000181e+09

# 4. Sort values by gdp_2017
* the values are represented in scientific notation, make sure to pay attention to the power of e

In [7]:
df_gdp_new.sort_values(by=['gdp_2017'])

                       Country      gdp_2017
243                     Tuvalu  4.061925e+07
177                      Nauru  1.095859e+08
122                   Kiribati  1.872762e+08
153           Marshall Islands  2.128810e+08
186                      Palau  2.863218e+08
..                         ...           ...
101           IDA & IBRD total  3.094160e+13
196  Post-demographic dividend  4.741500e+13
179               OECD members  5.025760e+13
93                 High income  5.141610e+13
257                      World  8.122920e+13

[249 rows x 2 columns]

# 5. Load Slavery Index Data into a new Data Frame

In [8]:
df_slavery = pd.read_csv("../data/clean_slavery_index.csv", header=1)
df_slavery.head()

,Country,"Population \n(from United Nations Population Division, World Population Prospects)",Region,"Est. prevalence of population in modern slavery (victims per 1,000 population)",Est. number of people in modern slavery,Factor One Governance Issues,Factor Two Nourishment and Access,Factor Three Inequality,Factor Four Disenfranchised Groups,Factor Five Effects of Conflict,...,NEG Government complicity (1.4.3),NEG State-imposed forced labour (1.8.1),Address risk,%.3,Supply chains,%.4,SUM/104,SUM Neg,TOTAL,Credit rating
0,Eritrea,"4,847,000",Africa,93.0,"451,000",71.0,50.6,33.7,48.1,25.9,...,-1.0,-1.0,1.5,21.4,0.0,0.0,1.4,-2.0,-2.0,D
1,Burundi,"10,199,000",Africa,40.0,"408,000",72.4,42.6,42.1,48.1,41.7,...,-1.0,-1.0,1.8,26.2,0.0,0.0,5.0,-2.0,10.7,C
2,Central African Republic,"4,546,000",Africa,22.3,"101,000",85.4,50.2,62.7,58.0,81.6,...,-1.0,0.0,1.5,21.4,0.0,0.0,1.7,-1.0,2.5,D
3,Mauritania,"4,182,000",Africa,21.4,"90,000",67.3,33.7,39.3,50.5,22.3,...,-1.0,0.0,2.5,35.7,0.0,0.0,5.3,-1.0,15.5,C
4,South Sudan,"11,882,000",Africa,20.5,"243,000",75.7,51.1,62.9,56.1,85.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_slavery.columns = df_slavery.columns.str.strip()
df_slavery.columns

Index(['Country',
       'Population \n(from United Nations Population Division, World Population Prospects)',
       'Region',
       'Est. prevalence of population in modern slavery (victims per 1,000 population)',
       'Est. number of people in modern slavery',
       'Factor One Governance Issues', 'Factor Two Nourishment and Access',
       'Factor Three Inequality', 'Factor Four Disenfranchised Groups',
       'Factor Five Effects of Conflict',
       'Final overall (normalised, weighted) vulnerability score',
       'Support survivors', '%', 'Criminal justice', '%.1', 'Coordination',
       '%.2', 'NEG Government  complicity (1.4.3)',
       'NEG State-imposed forced labour (1.8.1)', 'Address risk', '%.3',
       'Supply chains', '%.4', 'SUM/104', 'SUM Neg', 'TOTAL', 'Credit rating'],
      dtype='object')

# 5. Merge Table with the Slavery Index Data

In [13]:
reunion = pd.merge(df_slavery, df_gdp_new, on="Country" )
reunion

,Country,"Population \n(from United Nations Population Division, World Population Prospects)",Region,"Est. prevalence of population in modern slavery (victims per 1,000 population)",Est. number of people in modern slavery,Factor One Governance Issues,Factor Two Nourishment and Access,Factor Three Inequality,Factor Four Disenfranchised Groups,Factor Five Effects of Conflict,...,NEG State-imposed forced labour (1.8.1),Address risk,%.3,Supply chains,%.4,SUM/104,SUM Neg,TOTAL,Credit rating,gdp_2017
0,Burundi,"10,199,000",Africa,40.0,"408,000",72.4,42.6,42.1,48.1,41.7,...,-1.0,1.8,26.2,0.0,0.0,5.0,-2.0,10.7,C,3.172292e+09
1,Central African Republic,"4,546,000",Africa,22.3,"101,000",85.4,50.2,62.7,58.0,81.6,...,0.0,1.5,21.4,0.0,0.0,1.7,-1.0,2.5,D,2.072350e+09
2,Mauritania,"4,182,000",Africa,21.4,"90,000",67.3,33.7,39.3,50.5,22.3,...,0.0,2.5,35.7,0.0,0.0,5.3,-1.0,15.5,C,6.758391e+09
3,Sudan,"38,648,000",Africa,12.0,"465,000",80.7,46.6,42.4,37.0,87.4,...,0.0,2.3,33.3,0.0,0.0,5.2,-1.0,14.9,C,4.537913e+10
4,Chad,"14,009,000",Africa,12.0,"168,000",71.8,43.2,48.5,46.5,46.1,...,0.0,2.8,40.5,0.0,0.0,5.7,-1.0,16.7,C,1.000040e+10
5,Rwanda,"11,630,000",Africa,11.6,"134,000",56.6,40.8,40.0,55.7,34.0,...,-1.0,3.8,54.8,0.0,0.0,11.4,-2.0,33.6,CCC,9.253099e+09
6,Guinea,"12,092,000",Africa,7.8,"94,000",68.3,32.4,54.7,46.4,28.6,...,0.0,3.5,50.0,0.0,0.0,6.4,-1.0,19.3,C,1.033663e+10
7,Libya,"6,235,000",Africa,7.7,"48,000",81.4,23.0,49.6,28.1,63.1,...,-1.0,0.0,0.0,0.0,0.0,1.3,-2.0,-2.5,D,3.788324e+10
8,Nigeria,"181,182,000",Africa,7.7,"1,386,000",54.1,41.3,50.2,47.1,95.5,...,0.0,3.3,47.6,0.0,0.0,13.8,-1.0,45.8,B,3.757450e+11
9,Uganda,"40,145,000",Africa,7.6,"304,000",52.8,48.3,38.2,50.3,35.3,...,0.0,3.8,54.8,0.0,0.0,12.8,-1.0,42.0,B,3.075647e+10
10,Madagascar,"24,234,000",Africa,7.5,"182,000",54.4,46.8,51.0,56.8,17.3,...,-1.0,3.5,50.0,0.0,0.0,10.9,-2.0,31.8,CCC,1.317631e+10
11,Malawi,"17,574,000",Africa,7.5,"131,000",55.4,51.5,40.9,61.5,19.1,...,0.0,2.3,33.3,0.0,0.0,8.5,-1.0,26.8,CC,6.303292e+09
12,Guinea-Bissau,"1,771,000",Africa,7.5,"13,000",77.8,40.1,47.6,44.1,17.1,...,0.0,1.5,21.4,0.0,0.0,5.3,0.0,18.9,C,1.346842e+09
13,Liberia,"4,500,000",Africa,7.4,"33,000",55.0,44.0,44.1,54.9,18.2,...,0.0,3.5,50.0,0.0,0.0,8.9,0.0,31.7,CCC,3.285455e+09
14,Angola,"27,859,000",Africa,7.2,"199,000",60.2,43.4,48.2,48.5,19.8,...,0.0,3.8,54.8,0.0,0.0,9.3,-1.0,29.5,CC,1.221240e+11
15,Djibouti,"927,000",Africa,7.1,"7,000",66.8,38.0,33.9,48.1,21.3,...,0.0,3.3,47.6,0.0,0.0,9.9,0.0,35.3,CCC,2.751461e+09
16,Kenya,"47,236,000",Africa,6.9,"328,000",55.1,48.7,49.6,44.5,66.8,...,0.0,4.2,59.5,0.0,0.0,11.2,-1.0,36.5,CCC,7.896500e+10
17,Cameroon,"22,835,000",Africa,6.9,"157,000",65.9,36.5,46.2,46.3,53.9,...,0.0,3.5,50.0,0.0,0.0,8.1,-1.0,25.4,CC,3.500926e+10
18,Togo,"7,417,000",Africa,6.8,"50,000",70.0,31.5,45.3,42.3,17.1,...,0.0,1.5,21.4,0.0,0.0,6.6,0.0,23.6,CC,4.819950e+09
19,Niger,"19,897,000",Africa,6.7,"133,000",61.9,41.2,37.0,45.0,50.4,...,0.0,2.5,35.7,0.0,0.0,8.3,-1.0,25.9,CC,1.116606e+10
20,Zimbabwe,"15,777,000",Africa,6.7,"105,000",66.3,45.5,36.6,53.0,25.3,...,0.0,2.5,35.7,0.0,0.0,6.3,-1.0,19.0,C,2.204090e+10
21,Equatorial Guinea,"1,175,000",Africa,6.4,"7,000",68.4,40.8,36.7,48.5,10.1,...,0.0,1.8,26.2,0.0,0.0,3.4,-1.0,8.6,D,1.220091e+10
22,Ethiopia,"99,873,000",Africa,6.1,"614,000",62.4,47.5,27.3,34.6,55.3,...,0.0,3.3,47.6,0.0,0.0,11.2,-1.0,36.3,CCC,8.177079e+10
23,Zambia,"16,101,000",Africa,5.7,"92,000",45.8,54.4,44.9,49.1,13.1,...,0.0,2.8,40.5,0.0,0.0,8.9,0.0,31.8,CCC,2.586814e+10
24,Benin,"10,576,000",Africa,5.5,"58,000",51.1,28.8,39.9,35.3,15.8,...,0.0,3.7,52.4,0.0,0.0,10.6,0.0,37.7,CCC,1.270166e+10
25,Mozambique,"28,011,000",Africa,5.4,"152,000",48.6,48.3,40.5,48.1,30.0,...,0.0,3.0,42.9,0.0,0.0,12.4,-1.0,40.7,B,1.321908e+10
26,Sierra Leone,"7,237,000",Africa,5.0,"36,000",50.9,46.1,41.2,48.1,18.1,...,0.0,3.8,54.8,0.0,0.0,13.5,0.0,46.2,B,3.739578e+09
27,Ghana,"27,583,000",Africa,4.8,"133,000",52.6,29.1,42.0,53.7,21.6,...,0.0,2.8,40.5,0.2,8.3,8.7,-1.0,27.6,CC,5.899813e+10
28,Gabon,"1,930,000",Africa,4.8,"9,000",56.5,27.1,36.6,47.5,12.4,...,0.0,2.3,33.3,0.0,0.0,6.8,0.0,24.2,CC,1.492949e+10
29,Burkina Faso,"18,111,000",Africa,4.5,"82,000",58.4,31.6,40.3,35.2,26.2,...,0.0,3.0,42.9,0.0,0.0,10.0,0.0,35.7,CCC,1.416991e+10
30,Lesotho,"2,175,000",Africa,4.2,"9,000",53.8,50.7,44.6,41.9,18.6,...,0.0,3.0,42.9,0.0,0.0,10.7,0.0,38.3,CCC,2.405289e+09
31,Mali,"17,468,000",Africa,3.6,"62,000",55.3,24.4,35.5,35.9,66.3,...,-1.0,2.0,28.6,0.0,0.0,9.6,-1.0,30.8,CCC,1.537561e+10
32,Botswana,"2,209,000",Africa,3.4,"8,000",43.3,37.9,37.3,37.6,9.7,...,0.0,3.2,45.2,0.0,0.0,10.3,-1.0,33.2,CCC,1.740554e+10
33,Namibia,"2,426,000",Africa,3.3,"8,000",44.6,38.4,55.9,38.8,10.4,...,0.0,3.8,54.8,0.0,0.0,9.3,0.0,33.3,CCC,1.274175e+10
34,Senegal,"14,977,000",Africa,2.9,"43,000",43.9,34.8,35.6,41.0,30.9,...,0.0,3.8,54.8,0.0,0.0,13.2,0.0,47.1,B,2.099656e+10
35,South Africa,"55,291,000",Africa,2.8,"155,000",46.7,38.3,61.0,36.9,26.9,...,0.0,4.0,57.1,0.0,0.0,14.3,-1.0,47.4,B,3.495540e+11
36,Algeria,"39,872,000",Africa,2.7,"106,000",63.2,17.9,27.8,37.0,43.6,...,0.0,3.2,45.2,0.0,0.0,10.2,0.0,36.3,CCC,1.673890e+11
37,Morocco,"34,803,000",Africa,2.4,"85,000",60.7,18.8,38.1,35.7,22.0,...,0.0,5.0,71.4,0.0,0.0,10.2,0.0,36.5,CCC,1.097140e+11
38,Tunisia,"11,274,000",Africa,2.2,"25,000",47.2,15.4,34.8,31.9,33.7,...,0.0,4.0,57.1,0.0,0.0,12.4,0.0,44.3,B,3.980243e+10
39,Mauritius,"1,259,000",Africa,1.0,"1,000",25.5,17.7,33.6,31.1,12.2,...,0.0,3.5,50.0,0.0,0.0,9.8,0.0,34.9,CCC,1.325935e+10
40,Seychelles,"94,000",Africa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.524487e+09